import type { Application, TimelineEvent, Reminder, Interview } from "@/types";

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "app-1",
    userId: "dev",
    jobTitle: "Senior Frontend Engineer",
    company: "Stripe",
    status: "Interview",
    jobUrl: "https://stripe.com/jobs",
    location: "Dublin, Ireland",
    workMode: "Hybrid",
    salaryMin: 95000,
    salaryMax: 130000,
    currency: "EUR",
    source: "LinkedIn",
    deadline: undefined,
    notes: "Recruiter reached out on LinkedIn. Strong team, great eng culture. Prep system design.",
    createdAt: "2026-05-01T09:00:00Z",
    updatedAt: "2026-05-10T14:30:00Z",
  },
  {
    id: "app-2",
    userId: "dev",
    jobTitle: "Staff Software Engineer",
    company: "Linear",
    status: "Applied",
    jobUrl: "https://linear.app/careers",
    location: "Remote",
    workMode: "Remote",
    salaryMin: 180000,
    salaryMax: 230000,
    currency: "USD",
    source: "Company Website",
    deadline: undefined,
    notes: "Dream job. Love the product. Submitted through their website.",
    createdAt: "2026-05-03T11:00:00Z",
    updatedAt: "2026-05-03T11:00:00Z",
  },
  {
    id: "app-3",
    userId: "dev",
    jobTitle: "Product Engineer",
    company: "Vercel",
    status: "Technical Assessment",
    jobUrl: "https://vercel.com/careers",
    location: "Remote",
    workMode: "Remote",
    salaryMin: 160000,
    salaryMax: 200000,
    currency: "USD",
    source: "Twitter/X",
    deadline: "2026-05-20T23:59:00Z",
    notes: "Take-home project due May 20. Build a mini deployment pipeline UI.",
    createdAt: "2026-04-28T08:00:00Z",
    updatedAt: "2026-05-08T09:15:00Z",
  },
  {
    id: "app-4",
    userId: "dev",
    jobTitle: "Frontend Developer",
    company: "Intercom",
    status: "Screening",
    jobUrl: "https://intercom.com/careers",
    location: "London, UK",
    workMode: "Hybrid",
    salaryMin: 75000,
    salaryMax: 95000,
    currency: "GBP",
    source: "LinkedIn",
    deadline: undefined,
    notes: "Phone screen scheduled for next week.",
    createdAt: "2026-05-06T10:00:00Z",
    updatedAt: "2026-05-09T16:00:00Z",
  },
  {
    id: "app-5",
    userId: "dev",
    jobTitle: "Senior React Developer",
    company: "Shopify",
    status: "Rejected",
    jobUrl: "https://shopify.com/careers",
    location: "Remote",
    workMode: "Remote",
    salaryMin: 140000,
    salaryMax: 170000,
    currency: "CAD",
    source: "Referral",
    deadline: undefined,
    notes: "Got to final round but they went with an internal candidate. Good feedback on system design.",
    createdAt: "2026-04-15T09:00:00Z",
    updatedAt: "2026-05-05T11:00:00Z",
  },
  {
    id: "app-6",
    userId: "dev",
    jobTitle: "UI Engineer",
    company: "Figma",
    status: "Saved",
    jobUrl: "https://figma.com/careers",
    location: "San Francisco, CA",
    workMode: "Hybrid",
    salaryMin: 170000,
    salaryMax: 220000,
    currency: "USD",
    source: "Company Website",
    deadline: undefined,
    notes: "Bookmarked to apply. Need to tailor CV first.",
    createdAt: "2026-05-12T08:00:00Z",
    updatedAt: "2026-05-12T08:00:00Z",
  },
  {
    id: "app-7",
    userId: "dev",
    jobTitle: "Senior Full Stack Engineer",
    company: "Notion",
    status: "Final Interview",
    jobUrl: "https://notion.so/careers",
    location: "Remote",
    workMode: "Remote",
    salaryMin: 175000,
    salaryMax: 210000,
    currency: "USD",
    source: "LinkedIn",
    deadline: undefined,
    notes: "Final panel interview scheduled. Three rounds done. Great culture fit.",
    createdAt: "2026-04-20T10:00:00Z",
    updatedAt: "2026-05-11T14:00:00Z",
  },
];

export const MOCK_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: "ev-1",
    applicationId: "app-1",
    type: "Status Change",
    content: "Status changed from Applied → Interview",
    createdAt: "2026-05-10T14:30:00Z",
  },
  {
    id: "ev-2",
    applicationId: "app-1",
    type: "Note",
    content: "Spoke with Sarah (recruiter). Loop interviews will be 4 rounds, system design, coding, behavioural, and culture fit.",
    createdAt: "2026-05-09T10:00:00Z",
  },
  {
    id: "ev-3",
    applicationId: "app-1",
    type: "Status Change",
    content: "Status changed from Screening → Interview",
    createdAt: "2026-05-08T11:00:00Z",
  },
  {
    id: "ev-4",
    applicationId: "app-1",
    type: "Recruiter Update",
    content: "Initial recruiter screen went well. Moving to technical loop.",
    createdAt: "2026-05-06T15:00:00Z",
  },
  {
    id: "ev-5",
    applicationId: "app-1",
    type: "Status Change",
    content: "Status changed from Applied → Screening",
    createdAt: "2026-05-05T09:00:00Z",
  },
  {
    id: "ev-6",
    applicationId: "app-3",
    type: "Status Change",
    content: "Status changed from Interview → Technical Assessment",
    createdAt: "2026-05-08T09:15:00Z",
  },
  {
    id: "ev-7",
    applicationId: "app-3",
    type: "Note",
    content: "Take-home task received. Building a mini CI/CD status dashboard. Due May 20.",
    createdAt: "2026-05-08T09:20:00Z",
  },
  {
    id: "ev-8",
    applicationId: "app-7",
    type: "Status Change",
    content: "Status changed from Interview → Final Interview",
    createdAt: "2026-05-11T14:00:00Z",
  },
  {
    id: "ev-9",
    applicationId: "app-7",
    type: "Note",
    content: "Panel interview confirmed for next Tuesday at 2pm UTC. 3 panellists, Head of Eng, 2 senior engineers.",
    createdAt: "2026-05-11T14:05:00Z",
  },
];

export const MOCK_REMINDERS: Reminder[] = [
  {
    id: "rem-1",
    userId: "dev",
    applicationId: "app-1",
    application: { id: "app-1", jobTitle: "Senior Frontend Engineer", company: "Stripe" },
    title: "Follow up after interview",
    description: "Send thank-you email and ask about timeline",
    dueDate: "2026-05-15T09:00:00Z",
    completed: false,
    createdAt: "2026-05-10T14:30:00Z",
    updatedAt: "2026-05-10T14:30:00Z",
  },
  {
    id: "rem-2",
    userId: "dev",
    applicationId: "app-3",
    application: { id: "app-3", jobTitle: "Product Engineer", company: "Vercel" },
    title: "Submit take-home project",
    description: "Complete and submit the Vercel take-home assessment",
    dueDate: "2026-05-20T23:59:00Z",
    completed: false,
    createdAt: "2026-05-08T09:20:00Z",
    updatedAt: "2026-05-08T09:20:00Z",
  },
  {
    id: "rem-3",
    userId: "dev",
    applicationId: "app-2",
    application: { id: "app-2", jobTitle: "Staff Software Engineer", company: "Linear" },
    title: "Chase Linear application",
    description: "No response in 2 weeks, send a polite follow-up",
    dueDate: "2026-05-17T10:00:00Z",
    completed: false,
    createdAt: "2026-05-05T08:00:00Z",
    updatedAt: "2026-05-05T08:00:00Z",
  },
];

export const MOCK_INTERVIEWS: Interview[] = [
  {
    id: "int-1",
    userId: "dev",
    applicationId: "app-1",
    application: { id: "app-1", jobTitle: "Senior Frontend Engineer", company: "Stripe" },
    stage: "Technical Interview",
    type: "Video",
    scheduledAt: "2026-05-16T14:00:00Z",
    location: "Google Meet",
    notes: "System design round. Prep distributed systems and API design.",
    outcome: undefined,
    createdAt: "2026-05-10T14:30:00Z",
    updatedAt: "2026-05-10T14:30:00Z",
  },
  {
    id: "int-2",
    userId: "dev",
    applicationId: "app-7",
    application: { id: "app-7", jobTitle: "Senior Full Stack Engineer", company: "Notion" },
    stage: "Final Interview",
    type: "Video",
    scheduledAt: "2026-05-20T14:00:00Z",
    location: "Zoom",
    notes: "Panel interview with Head of Eng and two senior engineers.",
    outcome: undefined,
    createdAt: "2026-05-11T14:00:00Z",
    updatedAt: "2026-05-11T14:00:00Z",
  },
];
